name: Auto merge
on: 
  schedule:
    - cron: '0 0 * * 1'
    # scheduled for 00:00 every Monday

  workflow_dispatch:
    inputs:
      upstream:
        description: 'Upstream repository owner/name. Eg. exions/merge-upstream'
        required: true
        default: 'MarlinFirmware/Marlin'       # set the upstream repo
      upstream-branch:
        description: 'Upstream branch to merge from. Eg. master'
        required: true
        default: '2.0.x'           # set the upstream branch to merge from
      branch:
        description: 'Branch to merge to'
        required: true
        default: '2.0.x'         # set the branch to merge to

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 2.0.x             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: MarlinFirmware/Marlin     # set the upstream repo
          upstream-branch: 2.0.x   # set the upstream branch to merge from
          branch: 2.0.x          # set the branch to merge to
